server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/3306
        username: root
        password: 0000
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: false
                format_sql: true
                highlight_sql: true
logging:
    pattern:
        console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    level:
        org:
            hibernate:
                SQL: debug
                type.descriptor.sql: trace


# 암호화 secret key (HS256 알고리즘을 사용하기 위해, 256비트 보다 커야함(32글자 이상))
jwt:
    secret: DadFufN4Oui8Bfv3ScFj6R9fyJ9hD45E6AGFsXgFsRhT4YSdSb